# Generated by Django 4.2.6 on 2023-10-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_subscriptioncategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='categories',
            new_name='subscribedCategories',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='subscriptionUser',
        ),
        migrations.DeleteModel(
            name='SubscriptionCategory',
        ),
    ]
