# Generated by Django 4.2.6 on 2023-10-28 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_categories_subscription_subscribedcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscriptionCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
