# Generated by Django 4.2.6 on 2023-10-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_subscription_subscriptioncreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribedCategories',
            new_name='subscriptionCategories',
        ),
    ]
