# Generated by Django 4.2.6 on 2023-10-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_subscribedcategories_subscription_subscriptioncategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('fromSubscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.subscription')),
            ],
        ),
    ]
