# Generated by Django 4.2.6 on 2023-10-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_category_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_notification_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
